# Generated by Django 4.1.4 on 2022-12-19 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=20)),
                ('subject_thumb', models.ImageField(blank=True, null=True, upload_to='subject/')),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('video_title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('video_text', models.TextField(default='', null=True)),
                ('video_index', models.IntegerField()),
                ('video_date', models.DateField(auto_now_add=True)),
                ('video_pw', models.TextField(default='', null=True)),
                ('video_views', models.IntegerField(default=0)),
                ('video_likes', models.IntegerField(default=0)),
                ('video_thumb', models.ImageField(blank=True, null=True, upload_to='video/')),
                ('video_author', models.ForeignKey(on_delete=models.SET(0), to=settings.AUTH_USER_MODEL)),
                ('video_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.subject')),
            ],
        ),
        migrations.CreateModel(
            name='video_subscribe',
            fields=[
                ('sub_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('video_no', models.IntegerField(null=True)),
                ('sub_date', models.DateField(auto_now_add=True)),
                ('sub_user_id', models.ForeignKey(on_delete=models.SET(0), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='video_like',
            fields=[
                ('like_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('video_no', models.IntegerField(null=True)),
                ('like_date', models.DateField(auto_now_add=True)),
                ('like_user_id', models.ForeignKey(on_delete=models.SET(0), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='video_history',
            fields=[
                ('history_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateField(auto_now_add=True)),
                ('history_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('history_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.video')),
            ],
        ),
    ]
