# Generated by Django 4.1.4 on 2023-01-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_original',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
